repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
  - id: check-added-large-files         # Prevent giant files from being committed
  - id: check-ast         # Check whether the files parse as valid python
  - id: check-json         # Check json files for parseable syntax
  - id: check-merge-conflict         # Check for files that contain merge conflict strings
  - id: check-toml         # Checks toml files for parseable syntax
  - id: check-yaml         # Check yaml files for parseable syntax
  - id: debug-statements         # Check for debugger imports and `breakpoint()` calls in python
  - id: detect-private-key         # Detect the presence of private keys
  - id: end-of-file-fixer         # Ensures that files end with a newline
  - id: name-tests-test         # Verify that test files are named correctly
  - id: pretty-format-json         # Set a standard for formatting JSON files
    args: [--autofix, --no-sort-keys]
  - id: requirements-txt-fixer         # Sort entries in requirements.txt & requirement-dev.txt

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v1.6.1
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]

- repo: https://github.com/PyCQA/isort
  rev: 5.6.4
  hooks:
  - id: isort

- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black

- repo: https://github.com/nbQA-dev/nbQA     # for notebooks
  rev: 0.5.7
  hooks:
  - id: nbqa-black
    additional_dependencies: [black==20.8b1]
    args: [--nbqa-mutate]
  - id: nbqa-isort
    additional_dependencies: [isort==5.6.4]
    args: [--nbqa-mutate]

- repo: https://github.com/asottile/blacken-docs
  rev: v1.8.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==20.8b1]

- repo: https://gitlab.com/PyCQA/flake8
  rev: 3.8.4
  hooks:
  - id: flake8
    args: [--config=setup.cfg]
